version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
        name: setup
        command: sudo apt-get -qq -y install make g++ 
      - run:
          name: build
          command: make
      - run:
          name: run
          command: ./a.out
